// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqfqdeuhwbyrrzocliqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxZnFkZXVod2J5cnJ6b2NsaXFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyNDI5NjgsImV4cCI6MjA1NTgxODk2OH0.S-Wz3XYNMeoUhoH3qT3hR8nSxgb3BbmlV4KT7P7K80A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);